services:

    backend:
        build:
            context: ./ 
            dockerfile: ./backend/Dockerfile 
        ports:
            - 8080:8080 
        nom_conteneur: le backend 
        dépend de:
            - mongo
    mongo:
        image: mongo 
        expose:
            - 27017 
        ports:
            - 27017:27017 
        nom_conteneur: mongo
        volumes:
            - mongo_data:/var/lib/mongodb
    frontend:
        build:
            context: ./ 
            dockerfile: ./frontend/Dockerfile 
        ports:
            - 3000:3000 
        container_name: interface
    
volumes:
    - mongo:
